global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "aggregator-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["f1-aggregator:3100"]
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: [ "f1-gateway:3002" ]
