version: "3.8"

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: f1-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka-1:
    image: confluentinc/cp-kafka:7.5.0
    container_name: f1-kafka-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:

      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_MIN_INSYNC_REPLICAS: 2

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"


  kafka-2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: f1-kafka-2
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:

      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29093,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"


  kafka-3:
    image: confluentinc/cp-kafka:7.5.0
    container_name: f1-kafka-3
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    environment:

      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29094,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:29094,EXTERNAL://localhost:9094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"


  redis:
    image: redis:7-alpine
    container_name: f1-redis
    ports:
      - "6379:6379"


  postgres:
    image: postgres:15
    container_name: f1-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: f1
      POSTGRES_PASSWORD: f1
      POSTGRES_DB: telemetry
    volumes:
      - pgdata:/var/lib/postgresql/data


  akhq:
    image: tchiotludo/akhq
    container_name: f1-akhq
    depends_on:
      - kafka-1
    ports:
      - "9001:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka-1:29092,kafka-2:29093,kafka-3:29094"


  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: f1-kafka-init
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    entrypoint: /bin/bash
    command: -ec "

      echo 'Waiting for Kafka...';
      cub kafka-ready -b kafka-1:29092 1 40;

      echo 'Creating telemetry.raw';

      kafka-topics --create --if-not-exists \
      --topic telemetry.raw \
      --bootstrap-server kafka-1:29092 \
      --replication-factor 3 \
      --partitions 6 \
      --config retention.ms=86400000 \
      --config min.insync.replicas=2;

      echo 'Creating telemetry.snapshot';

      kafka-topics --create --if-not-exists \
      --topic telemetry.snapshot \
      --bootstrap-server kafka-1:29092 \
      --replication-factor 3 \
      --partitions 3 \
      --config retention.ms=-1;

      echo 'Creating system.logs';

      kafka-topics --create --if-not-exists \
      --topic system.logs \
      --bootstrap-server kafka-1:29092 \
      --replication-factor 3 \
      --partitions 3 \
      --config retention.ms=604800000;

      echo 'Topics successfully created';
      "

  aggregator-service:
    build:
      context: ../../services/aggregator-service
      dockerfile: Dockerfile
    container_name: f1-aggregator
    env_file:
       - ../../services/aggregator-service/.env
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - redis
      - postgres
    restart: unless-stopped

  ingestion-service:
    build:
      context: ../../services/ingestion-service
      dockerfile: Dockerfile
    container_name: f1-ingestion
    env_file:
      - ../../services/ingestion-service/.env
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    restart: unless-stopped

  gateway-service:
    build:
      context: ../../services/gateway
      dockerfile: Dockerfile
    container_name: f1-gateway
    env_file:
      - ../../services/gateway/.env
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - redis
      - postgres
    ports:
      - "3000:3000"
    restart: unless-stopped
volumes:
  pgdata: