export type AggregatorDeltaType =
    | "FULL_SNAPSHOT"

    | "SESSION_INFO_UPDATE"
    | "SESSION_STATUS_UPDATE"
    | "TRACK_STATUS_UPDATE"

    | "WEATHER_UPDATE"

    | "DRIVER_UPSERT"
    | "DRIVER_REMOVE"
    | "DRIVER_POSITION_UPDATE"
    | "DRIVER_TIMING_UPDATE"
    | "DRIVER_BEST_LAP_UPDATE"
    | "DRIVER_LAST_LAP_UPDATE"
    | "DRIVER_SECTORS_UPDATE"
    | "DRIVER_SPEEDS_UPDATE"
    | "DRIVER_BEST_SPEEDS_UPDATE"
    | "DRIVER_TYRE_UPDATE"
    | "DRIVER_STINTS_UPDATE"
    | "DRIVER_TRACK_STATE_UPDATE"

    | "RACE_CONTROL_MESSAGE_ADD"
    | "TEAM_RADIO_ADD";